image: java:8

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - build

stages:
  - build
  - package

build:gradle:
  stage: build
  script: ./gradlew build

build:docker:
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  stage: package
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
